### PR TITLE
Add resnet model, add bug fixes from master

### PR DESCRIPTION
**Pull request by Kipok**
For the resnet model, I simply imported necessary parts from tensorflow/models/official/resnet.
It's very short code now, it's not very flexible and not that nicely integrated in our toolkit, but should be good enough to run experiments for now. In order to make it work you will need to run

  git clone https://github.com/tensorflow/models.git tensorflow-models

from the root of OpenSeq2Seq.

### CODE REVIEW

**Comment by okuchaiev** [comment]
Why it is not encoder-decoder model?

**Comment by Kipok** [comment]
There are mainly 2 reasons for that:

  1. The input/output is not the same as for seq2seq models, thus, seq2seq class cannot be used directly => instead of making dummy encoder or decoder I decided to make it as a single model since we need a different base class anyway. In the future we might decide to either make seq2seq more flexible to accommodate this kind of models or make a more generic other class for such complete models that don't break into parts.

  2. The current implementation just imports complete model from TensorFlow's code => I couldn't break it into two parts without modifying/copying that code, which I didn't want to do for now (to integrate it faster and with less chance for bugs). But we will probably want to do that in the future so that we can easily modify the models.

**Comment by okuchaiev** [comment]
>>"The input/output is not the same as for seq2seq models, thus, seq2seq class cannot be used directly => instead of making dummy encoder or decoder I decided to make it as a single model since we need a different base class anyway."

- I do not understand this. Why can't this be done as a model with an encoder and empty_decoder which will just passes encoder's output to the loss?

>>"But we will probably want to do that in the future so that we can easily modify the models."
- Yes.

I think this should not be merged into master.

However, it is fine to merge this into "experiments" branch (which your PR asks) because we really have little time for this round of experiments and this is less bug prone for now.

**Comment by Kipok** [comment]
> I do not understand this. Why can't this be done as a model with an encoder and empty_decoder which will just passes encoder's output to the loss?

Because seq2seq class assumes that data layer produces src_sequence, src_length, tgt_sequence, tgt_length and this is not the case with imagenet. Same with encoders and decoders since they all necessary take sequences and lengths as their arguments. Thus, we need to either change that (e.g. take generic input from data_layer, but that's not simple as far as I can see) or to introduce additional generic class which I think is the right way to go if we want to support more non sequence-to-sequence cases.

**Comment by okuchaiev** [comment]
Why can't we have src_sequence = image, perhaps flattened to vector; src_length=None; tgt_sequence=1-hot class labels, tgt_length=None

>>"I think is the right way to go if we want to support more non sequence-to-sequence cases."
- This will open a whole new set of problems. Let's think seq2seq for now. Yes, ResNet does not benefit from being framed as seq2seq, but I think you can still formulate it as a seq2seq model with an empty decoder.

**Comment by Kipok** [comment]
> Why can't we have src_sequence = image, perhaps flattened to vector; src_length=None; tgt_sequence=1-hot class labels, tgt_length=None

I don't think there is any benefit from framing it as seq2seq, since it will actually result in more code and it will be less clean. But let's discuss it in person later. For now, let's just merge this in the experiments branch so that we can start doing experiments with it and fixing some possible bugs.

**Comment by borisgin** [comment]
Can we make decoder out of last fully connected layer?

**Comment by okuchaiev** [comment]
If we have ResNet encoder and a decoder which is just last layer, then the user would have all parts except of the data layer to start experimenting with image-to-text.

In general, we should be increasing the number of available encoders and decoders.

**Comment by okuchaiev** [comment]
You can merge it as-is if this blocks experiments. 

But then experiments branch will be incompatible with master until we reframe it as seq2seq

**Pull request merged**
