### PR TITLE
Added a script to allows new users to run the GNMT like model on wmt1…

### PR DESCRIPTION
**Pull request by matanhs**
…6 english to deutsch dataset,

examin the results on tensorboard and benchmark performance.
Please refer to try_gnmt_en2de.sh for instructions.
Slight alterations to run.py where made to monitor token/second performance.

### CODE REVIEW

**Comment by matanhs** [comment]
Can you send me the line you are trying to run?

בתאריך יום ב׳, 11 בדצמ׳ 2017, 16:10, מאת Oleksii Kuchaiev ‏<
notifications@github.com>:

**Comment by matanhs** [comment]
It was a default value bug, my bad I tested the script with the wrapper and
didn't try to run the native training without any parameters.

בתאריך יום ב׳, 11 בדצמ׳ 2017, 16:52, מאת Matan Haroush ‏<matan.hrs@gmail.com

**Comment by matanhs** [comment]
ping

**Comment by okuchaiev** [comment]
1dfddfdf

**Comment by okuchaiev** [comment]
1. Could you please put all your changes to "run.py" into something like "run_benchmark.py" ?
2. In "run_benchmark.py": remove all the code related to evaluation graph, checkpoint and summary saving, also remove inference function - we are only benchmarking training, right?
3. Rename "try_gnmt_en2de.sh" to something like "benchmark_gnmt_en2de.sh".
4. Maybe (not sure) it would be a good idea to cat few thousands lines from training sets instead of using full 4.5M - that way actual benchmark will start sooner.

Thanks!

**Comment by matanhs** [comment]
file updated to match requests

**Pull request merged**
